platform :ios, ‘8.0’
use_frameworks!

target 'Consort' do
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'SAMKeychain', '~> 1.5.2'
  pod 'Masonry', '~> 1.0.2'
  pod 'BlocksKit', '~> 2.2.5'
  pod 'MJExtension', '~> 3.0.13'
  pod 'MJRefresh', '~> 3.1.12'
  pod 'MLLabel', '~> 1.10.3’
  pod 'SDWebImage', '~> 4.0.0'
end