
platform :ios, ‘8.0’
inhibit_all_warnings!

target 'DouBan' do
  pod 'ReactiveObjC', '~> 3.0.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'SDWebImage', '~> 4.2.2'
  pod 'YYCache', '~> 1.0.4'
  pod 'JSONModel', '~> 1.7.0'
  pod 'FMDB', '~> 2.7.2'
  pod 'KVOController', '~> 1.2.0'
end
